CREATE UNLOGGED TABLE IF NOT EXISTS POSICAO_CLIENTE (
    CLIENTE_ID INTEGER NOT NULL,
    CLIENTE_LIMITE INTEGER NOT NULL,
    SALDO_LIMITE INTEGER NOT NULL CHECK (SALDO_LIMITE >= 0),
    SALDO_TOTAL INTEGER NOT NULL,
    PRIMARY KEY(CLIENTE_ID)
);

CREATE UNLOGGED TABLE IF NOT EXISTS EXTRATO_CLIENTE (
    DESCRICAO VARCHAR(10) NOT NULL,
    TIPO CHAR(1) CHECK (TIPO IN ('c', 'd')),
    VALOR INTEGER NOT NULL,
    REALIZADA_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENTE_ID INTEGER NOT NULL,
    CONSTRAINT FK_POSICAO_CLIENTE_CLIENTE_ID
		FOREIGN KEY(CLIENTE_ID)
		REFERENCES POSICAO_CLIENTE(CLIENTE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_CLIENTE_ID ON EXTRATO_CLIENTE (CLIENTE_ID);

CREATE OR REPLACE FUNCTION INSERT_CREDIT(ClientID INT, TransValor INT, TransDesc VARCHAR(10), TransRefDate TIMESTAMP)
RETURNS JSON
AS $$
DECLARE
    VAR_SALDO_LIMITE INT;
    VAR_SALDO_TOTAL INT;
BEGIN
    PERFORM pg_try_advisory_xact_lock(CLIENTE_ID) FROM POSICAO_CLIENTE WHERE CLIENTE_ID = ClientID;
    UPDATE POSICAO_CLIENTE
	SET SALDO_TOTAL = SALDO_TOTAL + TransValor,
		SALDO_LIMITE =
		    CASE WHEN (SALDO_LIMITE + TransValor) < CLIENTE_LIMITE THEN SALDO_LIMITE + TransValor ELSE CLIENTE_LIMITE END
    WHERE CLIENTE_ID = ClientID RETURNING SALDO_LIMITE, SALDO_TOTAL INTO VAR_SALDO_LIMITE, VAR_SALDO_TOTAL;

    -- CLIENTE NÃO ENCONTRADO
    IF (VAR_SALDO_LIMITE IS NULL OR VAR_SALDO_TOTAL IS NULL) THEN
        RAISE EXCEPTION 'Client not found';
    END IF;

    -- INSERIR MOVIMENTAÇÃO
    INSERT INTO EXTRATO_CLIENTE
        (DESCRICAO, TIPO, VALOR, CLIENTE_ID, REALIZADA_EM)
    VALUES
        (TransDesc, 'c', TransValor, ClientID, TransRefDate);
    RETURN json_build_object(
        'limite', VAR_SALDO_LIMITE,
        'saldo', VAR_SALDO_TOTAL
    );
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION INSERT_DEBIT(ClientID INT, TransValor INT, TransDesc VARCHAR(10))
RETURNS JSON
AS $$
DECLARE
    VAR_SALDO_LIMITE INT;
    VAR_SALDO_TOTAL INT;
BEGIN
    PERFORM pg_try_advisory_xact_lock(CLIENTE_ID) FROM POSICAO_CLIENTE WHERE CLIENTE_ID = ClientID;
    UPDATE POSICAO_CLIENTE
	SET SALDO_TOTAL = SALDO_TOTAL + TransValor,
		SALDO_LIMITE = CASE WHEN (SALDO_TOTAL + TransValor) < 0 then SALDO_LIMITE +  TransValor ELSE SALDO_LIMITE END
    WHERE CLIENTE_ID = ClientID RETURNING SALDO_LIMITE, SALDO_TOTAL INTO VAR_SALDO_LIMITE, VAR_SALDO_TOTAL;

    -- CLIENTE NÃO ENCONTRADO
    IF (VAR_SALDO_LIMITE IS NULL OR VAR_SALDO_TOTAL IS NULL) THEN
        RAISE EXCEPTION 'Client not found';
    END IF;

    -- INSERIR MOVIMENTAÇÃO
    INSERT INTO EXTRATO_CLIENTE
        (DESCRICAO, TIPO, VALOR, CLIENTE_ID)
    VALUES
        (TransDesc, 'd', TransValor, ClientID);
    RETURN json_build_object(
        'limite', VAR_SALDO_LIMITE,
        'saldo', VAR_SALDO_TOTAL
    );
END;
$$ LANGUAGE plpgsql;
